### DISCUSSION TITLE
How do i deploy this as a docker container?

### DISCUSSION THREAD

**Discussion by mlevett** [craigerl/aprsd#157] [Q&A]
Sorry for the stupid question, but can anyone advise how to deply this as a docker container?  If I try the command given on the docs to build it i get an error about buildx having one option.  

Usually I can just do a pull to get an image but that also errors out, and then im not sure how to add the configuration file.  is there a "dummies" style guide for this?  im new to docker so thats probably not helping.

Thanks!

Mat

**Comment by hemna** [comment]
Hey sorry about taking so long to reply.  I'm not getting notifications from github for the discussions.

So there is an existing docker container image on docker hub here:

https://hub.docker.com/r/hemna6969/aprsd

Here is my docker-compose for the w3w service, which I have taken down because what 3 words is now charging to use their API.

```
services:
  aprsd-w3w:
    image: hemna6969/aprsd:master
    container_name: aprsd-w3w
    ports:
      - 18864:18864
    volumes:
        - /home/waboring/docker/aprsd-w3w/config:/config
    restart: unless-stopped
    environment:
        - TZ=America/New_York
        - APRSD_PLUGINS=git+https://github.com/hemna/aprsd-w3w-plugin.git
    healthcheck:
        #test: ["CMD", "aprsd", "healthcheck", "--timeout", "5", "--config", "/config/aprsd.yml", "--loglevel", "DEBUG"]
        test:  aprsd healthcheck --config /config/aprsd.conf --loglevel DEBUG --timeout 5
        interval: 30s
        timeout: 5s
        retries: 5
    labels:
        com.centurylinklabs.watchtower.enable: "false"
        deunhealth.restart.on.unhealthy: "true"

  aprsd-w3w-admin:
    image: hemna6969/aprsd:master
    container_name: aprsd-w3w-admin
    volumes:
        - /home/waboring/docker/aprsd-w3w/config:/config
    restart: unless-stopped
    ports:
      - 8004:8000
    entrypoint: /app/admin.sh

networks:
  default:
    name: aprsd
    external: true
```
